version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: ai-dock-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  runner:
    build:
      context: .
      dockerfile: Dockerfile.runner
    container_name: ai-dock-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner_data:/workspace
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  redis_data:
  runner_data: